#ifndef SUSHME_EXAMPLE_H
#define SUSHME_EXAMPLE_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#endif /* SUSHME_EXAMPLE_H */
