#ifndef SUSHMEEXAMPLE_H
#define SUSHMEEXAMPLE_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

#endif /* SUSHMEEXAMPLE_H */
