#ifndef TEST_H
#define TEST_H

/* Some cross-platform definitions generated by autotools */
#if HAVE_CONFIG_H
#  include <config.h>
#endif /* HAVE_CONFIG_H */

/*
 * Example function
 */
extern void helloFunc(void);

#endif /* TEST_H */
